# Generated by Django 6.0.4 on 2026-04-29 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('event_created_at', models.DateTimeField(auto_now_add=True)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('points_awarded', models.IntegerField(default=0)),
                ('skill_tags', models.CharField(help_text='List skills separated by commas', max_length=255)),
                ('event_capacity', models.PositiveIntegerField(default=0, help_text='Maximum number of attendees allowed')),
                ('event_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('application_statement', models.TextField(blank=True, null=True)),
                ('application_applied_on', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('application_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_applications', to=settings.AUTH_USER_MODEL)),
                ('application_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.event')),
            ],
        ),
    ]
