# Generated by Django 6.0.4 on 2026-04-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='event',
            new_name='event_ID',
        ),
    ]
