# Generated by Django 6.0.4 on 2026-04-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_event_application_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
