# Generated by Django 6.0.4 on 2026-05-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='skill_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
