# Generated by Django 6.0.4 on 2026-06-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_skill_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
