# Generated by Django 6.0.4 on 2026-05-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedevent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='savedevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='SavedEvent',
        ),
    ]
