# Generated by Django 6.0.4 on 2026-05-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='student_staff_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_staff_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
