# Generated by Django 6.0.4 on 2026-06-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_registration_number_and_more'),
        ('core', '0007_interesttag_skilltag_remove_event_skill_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_profiles', to='core.interesttag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skilled_profiles', to='core.skilltag'),
        ),
    ]
