# Generated by Django 6.0.4 on 2026-05-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_discovery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedEvent',
        ),
    ]
